### ISSUE TITLE
Update the login component to have UI & functionality for creating an account

### ISSUE THREAD

**Issue by wagasky** [wagasky/movie-tracker#55]

**Comment by wagasky** [comment]
![image](https://user-images.githubusercontent.com/24358415/36055276-8f02e312-0db8-11e8-9175-6b116b59af8f.png)

**Comment by wagasky** [comment]
https://designmodo.com/login-form-examples/

**Comment by michellehoffman** [comment]
@NatBee @wagasky : I just did a first pass at this. We can style it differently, but I believe the functionality is pretty much there. I have a link below the sign in button that redirects to the register form.

<img width="481" alt="screen shot 2018-02-10 at 12 28 39 pm" src="https://user-images.githubusercontent.com/31316574/36065885-0543c636-0e5e-11e8-8cd4-5ec3a7d4c98c.png">
<img width="506" alt="screen shot 2018-02-10 at 12 28 44 pm" src="https://user-images.githubusercontent.com/31316574/36065886-0554981c-0e5e-11e8-817f-64c7b88d69d8.png">
